### PR TITLE
More pokemon

### PR DESCRIPTION
**Pull request by jjmakin**
Consistent filenames, more pokemon, several comments removed.
Generate pokemon name as text rather than image.

### CODE REVIEW

**Comment by derfreimann** [comment]
Awesome, mate! :D
Do you want me to upload it to the store or do you plan to release it as one of your own apps?

**Comment by jjmakin** [comment]
I'm happy for you to upload it to the store. Thanks for making this in the first place.
I've also got a colleague interested (@adstak) who may contribute as well.

**Comment by derfreimann** [comment]
Great, the more the merrier!
People would freak out if it would be available for Pebble Time and the coloured versions... ;D

**Comment by derfreimann** [comment]
compiled and published!

**Pull request closed without merging**
